language: python
branches:
  only:
    - develop
    - master
python:
  - "2.7"
sudo: false
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - python setup.py install
script:
  - py.test -v tests --cov threddsclient --cov-report term-missing
after_success:
  - coveralls
