language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
sudo: false
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - python setup.py install
script:
  - py.test -v tests
  - flake8
