# conda env create -f environment.yml
name: threddsclient
channels:
  - conda-forge
  - defaults
dependencies:
  - requests
  - beautifulsoup4
  - lxml
# tests
  - pytest
  - flake8
# release
  - bumpversion
